### ISSUE TITLE
Abbreviations not used consistently on transitions page

### ISSUE THREAD

**Issue by asquelt** [adamtow/mixeffect-localization#7]
![mixeffect screen shot](https://ze.psu.je/zAUXP/zrzut-ekranu-2021-05-28-o-14.46.20.png)

**Comment by asquelt** [comment]
@adamtow (1) and (2) are still other way around in build 94

we need (1) to be abbreviated (it's button) and (2) not to be abbreviated (menu, not a button)

**Comment by adamtow** [comment]
This should be fixed in the 1.0.6 release. I added a check to see if the size of the view is regular or compact, and now switch accordingly between normal and abbreviated versions of the string.

![IMG_1118](https://user-images.githubusercontent.com/3936001/121910494-bfa77f80-cce3-11eb-89ff-ff9960081e61.PNG)

**Comment by asquelt** [comment]
works fine in build 96, thank you!
